#%RAML 1.0 SecurityScheme
type: OAuth 2.0
describedBy:
  headers:
    Authorization: string
  responses:
    401:
      body:
        application/json:
          example:
            {
              "message": "unauthorized"
            }
    403:
      body:
        application/json:
          example:
            {
              "message": "forbidden"
            }
     
  